name: CD Example Production
on: 
push: branch:
  - main
jobs:
deploy:
  name: CD Example Production
  runs-on: ubuntu-latest
  steps:
    - name: Checkout My Code
      uses: actions/checkout@v4

    - name: SSH Connect
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          echo "Berhasil Konek ke Server"
          echo "Masuk dulu ke Folder YIS"
          cd /home/yis
          echo "Berhasil Masuk ke Folder YIS"

          echo "Mengecek apakah ini adalah git repository"
          if [ -d ".git" ]; then
            echo "Ada git repository"
            git pull origin main # Update repository ke branch main
          else
            echo "Gak ada git repository"
            git clone